#!/bin/tcsh
#xgettext --default-domain=BellePoule\
         #--output=BellePoule.pot\
         #--from-code=UTF-8\
         #--keyword=N_\
         #../../sources/*cpp ../../resources/glade/*glade

foreach file (`\ls *.po *pot`)
echo generating $file ...
xgettext --join-existing\
         --default-domain=BellePoule\
         --output=$file\
         --from-code=UTF-8\
         --keyword=N_\
         ../../sources/*cpp ../../resources/glade/*glade
end
