"    <style type=\"text/css\">\n"
"      body\n"
"      {\n"
"        background:  #434343;\n"
"        color:       #8ce566;\n"
"        font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;\n"
"      }\n"
"      .Title h1\n"
"      {\n"
"        margin:       5;\n"
"      }\n"
"      .Round\n"
"      {\n"
"        font-style:  normal;\n"
"        font-weight: bold;\n"
"      }\n"
"      .Table th\n"
"      {\n"
"        padding:     5px 5px 5px 5px;\n"
"      }\n"
"      .Table td\n"
"      {\n"
"        padding:     0px 5px 0px 5px;\n"
"        border:      20px;\n"
"      }\n"
"      .TableHeader\n"
"      {\n"
"        background:  #f58700;\n"
"        color:       Black;\n"
"      }\n"
"      .EvenRow\n"
"      {\n"
"        background:  #777777;\n"
"        color:       Black;\n"
"      }\n"
"      .OddRow\n"
"      {\n"
"        background:  #878787;\n"
"        color:       Black;\n"
"      }\n"
"      .Footer\n"
"      {\n"
"        color:       White;\n"
"      }\n"
"      A:link    {text-decoration: underline; color: #8ce566}\n"
"      A:visited {text-decoration: underline; color: #8ce566}\n"
"    </style>\n"
