"    <style type=\"text/css\">\n"
"      body\n"
"      {\n"
"        background:  #CCCCCC;\n"
"        color:       black;\n"
"        font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;\n"
"      }\n"
"      .Round\n"
"      {\n"
"        font-style:  normal;\n"
"        font-weight: bold;\n"
"      }\n"
"      .Table th\n"
"      {\n"
"        padding:     5px 5px 5px 5px;\n"
"      }\n"
"      .Table td\n"
"      {\n"
"        padding:     0px 5px 0px 5px;\n"
"      }\n"
"      .TableHeader\n"
"      {\n"
"        background:  #A69D00;\n"
"        color:       white;\n"
"      }\n"
"      .EvenRow\n"
"      {\n"
"        background:  #AAAAAA;\n"
"        color:       black;\n"
"      }\n"
"      .OddRow\n"
"      {\n"
"        background:  #BBBBBB;\n"
"        color:       black;\n"
"      }\n"
"    </style>\n"
