static gchar *fake_competion_list = "<Competitions>"
    "<Competition "
    "ID=\"406\" "
    "Name=\"Circuit National\" "
    "Weapon=\"Sabre\" "
    "Gender=\"M\" "
    "Category=\"Junior\"/>"

    "<Competition "
    "ID=\"4f90762b\" "
    "Name=\"Essai 6 tireurs\" "
    "Weapon=\"Sabre\" "
    "Gender=\"M\" "
    "Category=\"Poussin\"/>"
    "</Competitions>";

static gchar *fake_competion = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
"<!DOCTYPE CompetitionIndividuelle>"
"<!--"
"           By BellePoule (V3.0alpha12)"
""
"   http://betton.escrime.free.fr/index.php/bellepoule"
"-->"
"<CompetitionIndividuelle Couleur=\"3\" ID=\"4f90762b\" Annee=\"2012\" Arme=\"S\" Sexe=\"M\" Organisateur=\"GUC-Escrime\" Categorie=\"O\" Date=\"16.04.2012\" Appel=\"12:00\" Scratch=\"12:00\" Debut=\"12:00\" TitreLong=\"Essai 6 tireurs\" URLorganisateur=\"\" score_stuffing=\"1\" Lieu=\"\">"
" <Tireurs>"
"  <Tireur ID=\"6\" Classement=\"6\" Nom=\"LE BASTARD\" Prenom=\"Emma\" DateNaissance=\"20/03/1988\" Sexe=\"F\" Nation=\"FRA\" Club=\"GUINGAMP ARM\" Licence=\"003015623022\" Ranking=\"1012\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Tireur ID=\"3\" Classement=\"1\" Nom=\"CONTAMINE\" Prenom=\"Alice\" DateNaissance=\"03/02/1988\" Sexe=\"F\" Nation=\"FRA\" Club=\"RENNES MCB\" Licence=\"011165723035\" Ranking=\"1045\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Tireur ID=\"8\" Classement=\"3\" Nom=\"MOY\" Prenom=\"Anna\" DateNaissance=\"09/11/1987\" Sexe=\"F\" Nation=\"FRA\" Club=\"LANNION PTT\" Licence=\"002057323022\" Ranking=\"1074\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Tireur ID=\"1\" Classement=\"5\" Nom=\"BOURHIS\" Prenom=\"Annouck\" DateNaissance=\"21/03/1987\" Sexe=\"F\" Nation=\"FRA\" Club=\"H-FINISTERE\" Licence=\"006046423029\" Ranking=\"1074\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Tireur Nom=\"LE GOURRIEREC\" Prenom=\"Laureline\" DateNaissance=\"09/12/1988\" Sexe=\"F\" Nation=\"FRA\" Club=\"VANNES CE\" Licence=\"022122223056\" Ranking=\"1117\" Exporte=\"0\"/>"
"  <Tireur Nom=\"KALONJI\" Prenom=\"Marie\" DateNaissance=\"08/12/1989\" Sexe=\"F\" Nation=\"FRA\" Club=\"RENNES CSG\" Licence=\"013236023035\" Ranking=\"1130\" Exporte=\"0\"/>"
"  <Tireur Nom=\"SAILLARD\" Prenom=\"Chloe\" DateNaissance=\"06/12/1987\" Sexe=\"F\" Nation=\"FRA\" Club=\"ST MALO\" Licence=\"015128223035\" Ranking=\"1151\" Exporte=\"0\"/>"
"  <Tireur Nom=\"DANIEL\" Prenom=\"Margo\" DateNaissance=\"22/09/1987\" Sexe=\"F\" Nation=\"FRA\" Club=\"LORIENT SE\" Licence=\"020098523056\" Ranking=\"1168\" Exporte=\"0\"/>"
"  <Tireur Nom=\"GUEHO\" Prenom=\"Flavie\" DateNaissance=\"03/01/1988\" Sexe=\"F\" Nation=\"FRA\" Club=\"AURAY ESCRIM\" Licence=\"030040223056\" Ranking=\"1185\" Exporte=\"0\"/>"
"  <Tireur Nom=\"MORVAN\" Prenom=\"Emilie\" DateNaissance=\"29/10/1987\" Sexe=\"F\" Nation=\"FRA\" Club=\"LORIENT SE\" Licence=\"020105723056\" Ranking=\"1202\" Exporte=\"0\"/>"
"  <Tireur Nom=\"MACHARD\" Prenom=\"Manon\" DateNaissance=\"06/09/1988\" Sexe=\"F\" Nation=\"FRA\" Club=\"RENNES CSG\" Licence=\"013219423035\" Ranking=\"1222\" Exporte=\"0\"/>"
"  <Tireur Nom=\"HERY\" Prenom=\"Meline\" DateNaissance=\"29/10/1987\" Sexe=\"F\" Nation=\"FRA\" Club=\"ST MALO\" Licence=\"015137023035\" Ranking=\"1240\" Exporte=\"0\"/>"
"  <Tireur ID=\"7\" Classement=\"2\" Nom=\"LE TRAON\" Prenom=\"Coralie\" DateNaissance=\"03/04/1988\" Sexe=\"F\" Nation=\"FRA\" Club=\"LANNION PTT\" Licence=\"002062423022\" Ranking=\"1258\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Tireur ID=\"4\" Classement=\"4\" Nom=\"HUBERT\" Prenom=\"Aurore\" DateNaissance=\"20/02/1989\" Sexe=\"F\" Nation=\"FRA\" Club=\"ST MEEN LG\" Licence=\"012014123035\" Ranking=\"1274\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Tireur Nom=\"ETIENNE\" Prenom=\"Adelaide\" DateNaissance=\"04/02/1989\" Sexe=\"F\" Nation=\"FRA\" Club=\"RENNES CSG\" Licence=\"013225923035\" Ranking=\"1294\" Exporte=\"0\"/>"
"  <Tireur Nom=\"LELARGE\" Prenom=\"Enora\" DateNaissance=\"18/12/1989\" Sexe=\"F\" Nation=\"FRA\" Club=\"LORIENT SE\" Licence=\"020107323056\" Ranking=\"1312\" Exporte=\"0\"/>"
"  <Tireur Nom=\"SOULABAILLE\" Prenom=\"Anastasia\" DateNaissance=\"11/08/1989\" Sexe=\"F\" Nation=\"FRA\" Club=\"ST MALO\" Licence=\"015127223035\" Ranking=\"1329\" Exporte=\"0\"/>"
"  <Tireur Nom=\"GAUDIN\" Prenom=\"Edith\" DateNaissance=\"06/12/1987\" Sexe=\"F\" Nation=\"FRA\" Club=\"LORIENT SE\" Licence=\"020112023056\" Ranking=\"1349\" Exporte=\"0\"/>"
"  <Tireur Nom=\"JULLIEN\" Prenom=\"Lea\" DateNaissance=\"21/12/1987\" Sexe=\"F\" Nation=\"FRA\" Club=\"LORIENT SE\" Licence=\"020098623056\" Ranking=\"1365\" Exporte=\"0\"/>"
"  <Tireur Nom=\"LAURENS\" Prenom=\"Maelle\" DateNaissance=\"24/12/1988\" Sexe=\"F\" Nation=\"FRA\" Club=\"ST MEEN LG\" Licence=\"012017423035\" Ranking=\"1380\" Exporte=\"0\"/>"
"  <Tireur ID=\"2\" Classement=\"8\" Nom=\"CHEVALLIER\" Prenom=\"Leonie\" DateNaissance=\"28/10/1988\" Sexe=\"F\" Nation=\"FRA\" Club=\"DINAN EA\" Licence=\"007022323022\" Ranking=\"1410\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Tireur ID=\"5\" Classement=\"7\" Nom=\"LAQUAINE DEPIROU\" Prenom=\"Clara\" DateNaissance=\"04/09/1987\" Sexe=\"F\" Nation=\"FRA\" Club=\"RENNES MCB\" Licence=\"011160023035\" Ranking=\"0\" Exporte=\"0\" Statut=\"Q\"/>"
" </Tireurs>"
" <Arbitres>"
"  <Arbitre ID=\"1\" Nom=\"MOY\" Prenom=\"Anna\" DateNaissance=\"09/11/1987\" Sexe=\"F\" Nation=\"FRA\" Club=\"LANNION PTT\" Licence=\"002057323022\" Ranking=\"1074\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Arbitre ID=\"2\" Nom=\"LE TRAON\" Prenom=\"Coralie\" DateNaissance=\"03/04/1988\" Sexe=\"F\" Nation=\"FRA\" Club=\"LANNION PTT\" Licence=\"002062423022\" Ranking=\"1258\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Arbitre ID=\"3\" Nom=\"LE BASTARD\" Prenom=\"Emma\" DateNaissance=\"20/03/1988\" Sexe=\"F\" Nation=\"FRA\" Club=\"GUINGAMP ARM\" Licence=\"003015623022\" Ranking=\"1012\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Arbitre ID=\"4\" Nom=\"CHEVALLIER\" Prenom=\"Leonie\" DateNaissance=\"28/10/1988\" Sexe=\"F\" Nation=\"FRA\" Club=\"DINAN EA\" Licence=\"007022323022\" Ranking=\"1410\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Arbitre ID=\"5\" Nom=\"BOURHIS\" Prenom=\"Annouck\" DateNaissance=\"21/03/1987\" Sexe=\"F\" Nation=\"FRA\" Club=\"H-FINISTERE\" Licence=\"006046423029\" Ranking=\"1074\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Arbitre ID=\"6\" Nom=\"LAQUAINE DEPIROU\" Prenom=\"Clara\" DateNaissance=\"04/09/1987\" Sexe=\"F\" Nation=\"FRA\" Club=\"RENNES MCB\" Licence=\"011160023035\" Ranking=\"0\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Arbitre ID=\"7\" Nom=\"CONTAMINE\" Prenom=\"Alice\" DateNaissance=\"03/02/1988\" Sexe=\"F\" Nation=\"FRA\" Club=\"RENNES MCB\" Licence=\"011165723035\" Ranking=\"1045\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Arbitre ID=\"8\" Nom=\"HUBERT\" Prenom=\"Aurore\" DateNaissance=\"20/02/1989\" Sexe=\"F\" Nation=\"FRA\" Club=\"ST MEEN LG\" Licence=\"012014123035\" Ranking=\"1274\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Arbitre ID=\"9\" Nom=\"LAURENS\" Prenom=\"Maelle\" DateNaissance=\"24/12/1988\" Sexe=\"F\" Nation=\"FRA\" Club=\"ST MEEN LG\" Licence=\"012017423035\" Ranking=\"1380\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Arbitre ID=\"10\" Nom=\"MACHARD\" Prenom=\"Manon\" DateNaissance=\"06/09/1988\" Sexe=\"F\" Nation=\"FRA\" Club=\"RENNES CSG\" Licence=\"013219423035\" Ranking=\"1222\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Arbitre ID=\"11\" Nom=\"ETIENNE\" Prenom=\"Adelaide\" DateNaissance=\"04/02/1989\" Sexe=\"F\" Nation=\"FRA\" Club=\"RENNES CSG\" Licence=\"013225923035\" Ranking=\"1294\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Arbitre ID=\"12\" Nom=\"KALONJI\" Prenom=\"Marie\" DateNaissance=\"08/12/1989\" Sexe=\"F\" Nation=\"FRA\" Club=\"RENNES CSG\" Licence=\"013236023035\" Ranking=\"1130\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Arbitre ID=\"13\" Nom=\"SOULABAILLE\" Prenom=\"Anastasia\" DateNaissance=\"11/08/1989\" Sexe=\"F\" Nation=\"FRA\" Club=\"ST MALO\" Licence=\"015127223035\" Ranking=\"1329\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Arbitre ID=\"14\" Nom=\"SAILLARD\" Prenom=\"Chloe\" DateNaissance=\"06/12/1987\" Sexe=\"F\" Nation=\"FRA\" Club=\"ST MALO\" Licence=\"015128223035\" Ranking=\"1151\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Arbitre ID=\"15\" Nom=\"HERY\" Prenom=\"Meline\" DateNaissance=\"29/10/1987\" Sexe=\"F\" Nation=\"FRA\" Club=\"ST MALO\" Licence=\"015137023035\" Ranking=\"1240\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Arbitre ID=\"16\" Nom=\"DANIEL\" Prenom=\"Margo\" DateNaissance=\"22/09/1987\" Sexe=\"F\" Nation=\"FRA\" Club=\"LORIENT SE\" Licence=\"020098523056\" Ranking=\"1168\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Arbitre ID=\"17\" Nom=\"JULLIEN\" Prenom=\"Lea\" DateNaissance=\"21/12/1987\" Sexe=\"F\" Nation=\"FRA\" Club=\"LORIENT SE\" Licence=\"020098623056\" Ranking=\"1365\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Arbitre ID=\"18\" Nom=\"MORVAN\" Prenom=\"Emilie\" DateNaissance=\"29/10/1987\" Sexe=\"F\" Nation=\"FRA\" Club=\"LORIENT SE\" Licence=\"020105723056\" Ranking=\"1202\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Arbitre ID=\"19\" Nom=\"LELARGE\" Prenom=\"Enora\" DateNaissance=\"18/12/1989\" Sexe=\"F\" Nation=\"FRA\" Club=\"LORIENT SE\" Licence=\"020107323056\" Ranking=\"1312\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Arbitre ID=\"20\" Nom=\"GAUDIN\" Prenom=\"Edith\" DateNaissance=\"06/12/1987\" Sexe=\"F\" Nation=\"FRA\" Club=\"LORIENT SE\" Licence=\"020112023056\" Ranking=\"1349\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Arbitre ID=\"21\" Nom=\"LE GOURRIEREC\" Prenom=\"Laureline\" DateNaissance=\"09/12/1988\" Sexe=\"F\" Nation=\"FRA\" Club=\"VANNES CE\" Licence=\"022122223056\" Ranking=\"1117\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Arbitre ID=\"22\" Nom=\"GUEHO\" Prenom=\"Flavie\" DateNaissance=\"03/01/1988\" Sexe=\"F\" Nation=\"FRA\" Club=\"AURAY ESCRIM\" Licence=\"030040223056\" Ranking=\"1185\" Exporte=\"0\" Statut=\"Q\"/>"
"  <Arbitre ID=\"23\" Nom=\"FARINES\" Prenom=\"Emmanuel\" DateNaissance=\"27.12.1972\" Sexe=\"M\" Nation=\"FRA\" Ligue=\"PARIS\" Licence=\"270750360248\" Exporte=\"0\"/>"
"  <Arbitre ID=\"24\" Nom=\"GARNERET\" Prenom=\"Xavier\" DateNaissance=\"11.11.1986\" Sexe=\"M\" Nation=\"FRA\" Ligue=\"CRETEIL\" Licence=\"260941860499\" Exporte=\"0\"/>"
"  <Arbitre ID=\"25\" Nom=\"HARENDARCZYK\" Prenom=\"Richard\" DateNaissance=\"18.04.1969\" Sexe=\"M\" Nation=\"FRA\" Ligue=\"CRETEIL\" Licence=\"260931611113\" Exporte=\"0\"/>"
"  <Arbitre ID=\"26\" Nom=\"LECLERC\" Prenom=\"Franck\" DateNaissance=\"28.09.1962\" Sexe=\"M\" Nation=\"FRA\" Ligue=\"MIDI-PYRENEES\" Licence=\"250650240017\" Exporte=\"0\"/>"
"  <Arbitre ID=\"27\" Nom=\"JAMMES\" Prenom=\"Alizee\" DateNaissance=\"05.04.1988\" Sexe=\"F\" Nation=\"FRA\" Ligue=\"CENTRE\" Licence=\"200450232738\" Exporte=\"0\"/>"
"  <Arbitre ID=\"28\" Nom=\"FROMET\" Prenom=\"Joris\" DateNaissance=\"23.02.1986\" Sexe=\"M\" Nation=\"FRA\" Ligue=\"CENTRE\" Licence=\"200370170377\" Exporte=\"0\" Statut=\"F\"/>"
"  <Arbitre ID=\"29\" Nom=\"SCHAFIER\" Prenom=\"Maxime\" DateNaissance=\"20.07.1985\" Sexe=\"M\" Nation=\"FRA\" Ligue=\"NORD-PAS DE CALAIS\" Licence=\"130590100754\" Exporte=\"0\"/>"
"  <Arbitre ID=\"30\" Nom=\"FIHUE\" Prenom=\"Lysiane\" DateNaissance=\"09.04.1991\" Sexe=\"F\" Nation=\"FRA\" Ligue=\"HAUTE-NORMANDIE\" Licence=\"110270040551\" Exporte=\"0\"/>"
"  <Arbitre ID=\"31\" Nom=\"ROUSSET\" Prenom=\"Nicolas\" DateNaissance=\"07.07.1988\" Sexe=\"M\" Nation=\"FRA\" Ligue=\"BOURGOGNE\" Licence=\"090210011412\" Exporte=\"0\"/>"
"  <Arbitre ID=\"32\" Nom=\"PACAULT\" Prenom=\"Yvon\" DateNaissance=\"18.09.1956\" Sexe=\"M\" Nation=\"FRA\" Ligue=\"AQUITAINE\" Licence=\"040640211660\" Exporte=\"0\"/>"
" </Arbitres>"
" <Phases PhaseEnCours=\"3\">"
"  <TourDePoules PhaseID=\"1\" ID=\"\" ScoreMax=\"5\" RatioQualifies=\"100\" NbQualifies=\"8\" RepartitionEquilibre=\"1\" Decalage=\"Aucun\" NbDePoules=\"2\" PhaseSuivanteDesQualifies=\"3\" NbQualifiesParIndice=\"4\">"
"   <Tireur REF=\"6\" RangInitial=\"1\" RangFinal=\"6\" Statut=\"Q\"/>"
"   <Tireur REF=\"3\" RangInitial=\"2\" RangFinal=\"1\" Statut=\"Q\"/>"
"   <Tireur REF=\"8\" RangInitial=\"4\" RangFinal=\"3\" Statut=\"Q\"/>"
"   <Tireur REF=\"1\" RangInitial=\"3\" RangFinal=\"5\" Statut=\"Q\"/>"
"   <Tireur REF=\"7\" RangInitial=\"5\" RangFinal=\"2\" Statut=\"Q\"/>"
"   <Tireur REF=\"4\" RangInitial=\"6\" RangFinal=\"4\" Statut=\"Q\"/>"
"   <Tireur REF=\"2\" RangInitial=\"7\" RangFinal=\"8\" Statut=\"Q\"/>"
"   <Tireur REF=\"5\" RangInitial=\"8\" RangFinal=\"7\" Statut=\"Q\"/>"
"   <Poule ID=\"1\">"
"    <Tireur REF=\"6\" NoDansLaPoule=\"1\" NbVictoires=\"1\" NbMatches=\"3\" TD=\"9\" TR=\"11\" RangPoule=\"3\"/>"
"    <Tireur REF=\"8\" NoDansLaPoule=\"2\" NbVictoires=\"2\" NbMatches=\"3\" TD=\"13\" TR=\"10\" RangPoule=\"2\"/>"
"    <Tireur REF=\"5\" NoDansLaPoule=\"3\" NbVictoires=\"1\" NbMatches=\"3\" TD=\"6\" TR=\"13\" RangPoule=\"4\"/>"
"    <Tireur REF=\"7\" NoDansLaPoule=\"4\" NbVictoires=\"2\" NbMatches=\"3\" TD=\"11\" TR=\"5\" RangPoule=\"1\"/>"
"    <Match ID=\"1\">"
"     <Tireur REF=\"6\" Score=\"0\" Statut=\"D\"/>"
"     <Tireur REF=\"7\" Score=\"5\" Statut=\"V\"/>"
"    </Match>"
"    <Match ID=\"2\">"
"     <Tireur REF=\"8\" Score=\"3\" Statut=\"D\"/>"
"     <Tireur REF=\"5\" Score=\"5\" Statut=\"V\"/>"
"    </Match>"
"    <Match ID=\"3\">"
"     <Tireur REF=\"6\" Score=\"5\" Statut=\"V\"/>"
"     <Tireur REF=\"5\" Score=\"1\" Statut=\"D\"/>"
"    </Match>"
"    <Match ID=\"4\">"
"     <Tireur REF=\"8\" Score=\"5\" Statut=\"V\"/>"
"     <Tireur REF=\"7\" Score=\"1\" Statut=\"D\"/>"
"    </Match>"
"    <Match ID=\"5\">"
"     <Tireur REF=\"5\" Score=\"0\" Statut=\"D\"/>"
"     <Tireur REF=\"7\" Score=\"5\" Statut=\"V\"/>"
"    </Match>"
"    <Match ID=\"6\">"
"     <Tireur REF=\"6\" Score=\"4\" Statut=\"D\"/>"
"     <Tireur REF=\"8\" Score=\"5\" Statut=\"V\"/>"
"    </Match>"
"   </Poule>"
"   <Poule ID=\"2\">"
"    <Tireur REF=\"1\" NoDansLaPoule=\"1\" NbVictoires=\"2\" NbMatches=\"3\" TD=\"10\" TR=\"9\" RangPoule=\"3\"/>"
"    <Tireur REF=\"3\" NoDansLaPoule=\"2\" NbVictoires=\"2\" NbMatches=\"3\" TD=\"13\" TR=\"7\" RangPoule=\"1\"/>"
"    <Tireur REF=\"2\" NoDansLaPoule=\"3\" NbVictoires=\"0\" NbMatches=\"3\" TD=\"5\" TR=\"15\" RangPoule=\"4\"/>"
"    <Tireur REF=\"4\" NoDansLaPoule=\"4\" NbVictoires=\"2\" NbMatches=\"3\" TD=\"12\" TR=\"9\" RangPoule=\"2\"/>"
"    <Match ID=\"1\">"
"     <Tireur REF=\"1\" Score=\"0\" Statut=\"D\"/>"
"     <Tireur REF=\"4\" Score=\"5\" Statut=\"V\"/>"
"    </Match>"
"    <Match ID=\"2\">"
"     <Tireur REF=\"3\" Score=\"5\" Statut=\"V\"/>"
"     <Tireur REF=\"2\" Score=\"0\" Statut=\"D\"/>"
"    </Match>"
"    <Match ID=\"3\">"
"     <Tireur REF=\"1\" Score=\"5\" Statut=\"V\"/>"
"     <Tireur REF=\"2\" Score=\"1\" Statut=\"D\"/>"
"    </Match>"
"    <Match ID=\"4\">"
"     <Tireur REF=\"3\" Score=\"5\" Statut=\"V\"/>"
"     <Tireur REF=\"4\" Score=\"2\" Statut=\"D\"/>"
"    </Match>"
"    <Match ID=\"5\">"
"     <Tireur REF=\"2\" Score=\"4\" Statut=\"D\"/>"
"     <Tireur REF=\"4\" Score=\"5\" Statut=\"V\"/>"
"    </Match>"
"    <Match ID=\"6\">"
"     <Tireur REF=\"1\" Score=\"5\" Statut=\"V\"/>"
"     <Tireur REF=\"3\" Score=\"3\" Statut=\"D\"/>"
"    </Match>"
"   </Poule>"
"  </TourDePoules>"
"  <PhaseDeTableaux PhaseID=\"3\" ID=\"\" ScoreMax=\"10\" RatioQualifies=\"100\" NbQualifies=\"8\" PlacesTirees=\"0\">"
"   <Tireur REF=\"3\" RangInitial=\"1\" Statut=\"Q\"/>"
"   <Tireur REF=\"7\" RangInitial=\"2\" Statut=\"Q\"/>"
"   <Tireur REF=\"8\" RangInitial=\"3\" Statut=\"Q\"/>"
"   <Tireur REF=\"4\" RangInitial=\"4\" Statut=\"Q\"/>"
"   <Tireur REF=\"1\" RangInitial=\"5\" Statut=\"Q\"/>"
"   <Tireur REF=\"6\" RangInitial=\"6\" Statut=\"Q\"/>"
"   <Tireur REF=\"5\" RangInitial=\"7\" Statut=\"Q\"/>"
"   <Tireur REF=\"2\" RangInitial=\"8\" Statut=\"Q\"/>"
"   <SuiteDeTableaux ID=\"0\" Titre=\"Place N°1\" NbDeTableaux=\"3\">"
"    <Tableau ID=\"A8\" Titre=\"Tableau de 8\" Taille=\"8\">"
"     <Match ID=\"1\">"
"      <Arbitre REF=\"1\"/>"
"      <Arbitre REF=\"5\"/>"
"      <Tireur REF=\"3\"/>"
"      <Tireur REF=\"2\"/>"
"     </Match>"
"     <Match ID=\"2\">"
"      <Arbitre REF=\"4\"/>"
"      <Arbitre REF=\"2\"/>"
"      <Tireur REF=\"1\" Score=\"10\" Statut=\"V\"/>"
"      <Tireur REF=\"4\" Score=\"5\" Statut=\"D\"/>"
"     </Match>"
"     <Match ID=\"3\">"
"      <Tireur REF=\"8\"/>"
"      <Tireur REF=\"6\"/>"
"     </Match>"
"     <Match ID=\"4\">"
"      <Arbitre REF=\"4\"/>"
"      <Arbitre REF=\"3\"/>"
"      <Tireur REF=\"5\"/>"
"      <Tireur REF=\"7\"/>"
"     </Match>"
"    </Tableau>"
"    <Tableau ID=\"A4\" Titre=\"Demi-finale\" Taille=\"4\">"
"     <Match ID=\"1\">"
"      <Tireur REF=\"1\"/>"
"     </Match>"
"     <Match ID=\"2\"/>"
"    </Tableau>"
"    <Tableau ID=\"A2\" Titre=\"Finale\" Taille=\"2\">"
"     <Match ID=\"1\"/>"
"    </Tableau>"
"   </SuiteDeTableaux>"
"  </PhaseDeTableaux>"
"  <ClassementGeneral PhaseID=\"4\" ID=\"\" RatioQualifies=\"100\" NbQualifies=\"0\"/>"
" </Phases>"
"</CompetitionIndividuelle>";
