#!/usr/bin/awk -f
BEGIN \
{
  FS="[;,]"
  OUTPUT = (ARGV[1]) (".html")
  COUNT = 0

  print "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">" > OUTPUT
  print "<html xmlns=\"http://www.w3.org/1999/xhtml\">" > OUTPUT
  print "<head>" > OUTPUT
  print "<meta http-equiv=\"content-type\" content=\"text/html; charset=iso-8859-1\" />" > OUTPUT
  print "<title>"ARGV[1]"</title>" > OUTPUT
  print "<link rel=\"stylesheet\" href=\"style.css\" type=\"text/css\" media=\"all\" />" > OUTPUT
  print "<link rel=\"stylesheet\" href=\"print.css\" type=\"text/css\" media=\"print\" />" > OUTPUT
  print "</head>" > OUTPUT
  print "" > OUTPUT
  print "<body>" > OUTPUT
  print "" > OUTPUT
  print "  <h1>" > OUTPUT
  print "  "ARGV[1] > OUTPUT
  print "  </h1>" > OUTPUT
  print "  <h3>Classement général</h3>" > OUTPUT
  print "<table class=\"liste\" summary=\"Classement général\">" > OUTPUT
  print "<tr>" > OUTPUT
  print "  <th class=\"HGBD\">&nbsp;Rg&nbsp;</th>" > OUTPUT
  print "  <th class=\"HBD\">&nbsp;Nom&nbsp;</th>" > OUTPUT
  print "  <th class=\"HBD\">&nbsp;Prénom&nbsp;</th>" > OUTPUT
  print "  <th class=\"HBD\">&nbsp;Nation&nbsp;</th>" > OUTPUT
  print "  <th class=\"HBD\">&nbsp;Club&nbsp;</th>" > OUTPUT
  print "</tr>" > OUTPUT
}

{
  if (NF == 17)
  {
    COUNT = COUNT+1

    if ($16 == "1")
    {
      print "<tr bgcolor=\"#F7F74C\">" > OUTPUT
    }
    else if ($16 == "2")
    {
      print "<tr bgcolor=\"#C3C3C3\">" > OUTPUT
    }
    else if ($16 == "3")
    {
      print "<tr bgcolor=\"#B58231\">" > OUTPUT
    }
    else
    {
      print "<tr bgcolor=\"#FFCCCC\">" > OUTPUT
    }
    print "  <td class=\"GBD\" align=\"right\">&nbsp;" $16 "&nbsp;</td>" > OUTPUT
    print "  <td class=\"BD\">&nbsp;" $1 "&nbsp;</td>" > OUTPUT
    print "  <td class=\"BD\">&nbsp;" $2 "&nbsp;</td>" > OUTPUT
    print "  <td class=\"BD\">&nbsp;&nbsp;" $5 "&nbsp;</td>" > OUTPUT
    print "  <td class=\"BD\">&nbsp;&nbsp;" $12 "&nbsp;</td>" > OUTPUT
    print "</tr>" > OUTPUT
    print "" > OUTPUT
  }
}

END \
{
  print "</table>" > OUTPUT
  print "</body>" > OUTPUT
  print "</html>" > OUTPUT

  print COUNT " fencers converted"
}
